export const runes = [{
  label: '정밀',
  labelEn: 'precision',
  slug: 'precision',
  value: 8000,
  imgValue: 7201,
  subRunes: [
    { label: '정복자', labelEn: 'Conqueror', slug: 'conqueror', value: 8005 },
    { label: '치명적 속도', labelEn: 'Lethal Tempo', slug: 'lethalTempo', value: 8008 },
    { label: '기민한 발놀림', labelEn: 'Fleet Footwork', slug: 'fleetFootwork', value: 8021 },
    { label: '집중 공격', labelEn: 'Press the Attack', slug: 'pressTheAttack', value: 8010 },
    { label: '과다치유', labelEn: 'Overheal', slug: 'overheal', value: 9111 },
    { label: '승전보', labelEn: 'Triumph', slug: 'triumph', value: 8009 },
    { label: '전설: 민첩함', labelEn: 'Legend: Alacrity', slug: 'legendAlacrity', value: 9104 },
    { label: '전설: 강인함', labelEn: 'Legend: Tenacity', slug: 'legendTenacity', value: 9105 },
    { label: '전설: 핏빛 길', labelEn: 'Legend: Bloodline', slug: 'legendBloodline', value: 9103 },
    { label: '최후의 일격', labelEn: 'Coup de Grace', slug: 'coupDeGrace', value: 8014 },
    { label: '체력차 극복', labelEn: 'Cut Down', slug: 'cutDown', value: 8017 },
    { label: '최후의 저항', labelEn: 'Last Stand', slug: 'lastStand', value: 8299 },
  ],
}, {
  label: '지배',
  labelEn: 'domination',
  slug: 'domination',
  value: 8100,
  imgValue: 7200,
  subRunes: [
    { label: '감전', labelEn: 'Electrocute', slug: 'electrocute', value: 8112 },
    { label: '포식자', labelEn: 'Predator', slug: 'predator', value: 8124 },
    { label: '어둠의 수확', labelEn: 'Dark Harvest', slug: 'darkHarvest', value: 8128 },
    { label: '칼날비', labelEn: 'Hail of Blades', slug: 'hailOfBlades', value: 9923 },
    { label: '비열한 한 방', labelEn: 'Cheap Shot', slug: 'cheapShot', value: 8126 },
    { label: '돌발 일격', labelEn: 'Sudden Impact', slug: 'suddenImpact', value: 8139 },
    { label: '유령 포로', labelEn: 'Ghost Poro', slug: 'ghostPoro', value: 8120 },
    { label: '좀비 와드', labelEn: 'Zombie Ward', slug: 'zombieWard', value: 8136 },
    { label: '망자의 발자취', labelEn: 'Eyeball Collection', slug: 'eyeballCollection', value: 8138 },
    { label: '끈질긴 사냥꾼', labelEn: 'Relentless Hunter', slug: 'relentlessHunter', value: 8105 },
    { label: '포식자 사냥꾼', labelEn: 'Ingenious Hunter', slug: 'ingeniousHunter', value: 8106 },
    { label: '궁극의 사냥꾼', labelEn: 'Ultimate Hunter', slug: 'ultimateHunter', value: 8104 },
  ],
}, {
  label: '마법',
  labelEn: 'sorcery',
  slug: 'sorcery',
  value: 8200,
  imgValue: 7202,
  subRunes: [
    { label: '콩콩이 소환', labelEn: 'Summon Aery', slug: 'summonAery', value: 8214 },
    { label: '신비로운 유성', labelEn: 'Arcane Comet', slug: 'arcaneComet', value: 8229 },
    { label: '난입', labelEn: 'Phase Rush', slug: 'phaseRush', value: 8230 },
    { label: '마나순환 팔찌', labelEn: 'Manaflow Band', slug: 'manaflowBand', value: 8226 },
    { label: '빛의 망토', labelEn: 'Nimbus Cloak', slug: 'nimbusCloak', value: 8275 },
    { label: '깨달음', labelEn: 'Transcendence', slug: 'transcendence', value: 8234 },
    { label: '주문 작열', labelEn: 'Scorch', slug: 'scorch', value: 8237 },
    { label: '물 위를 걷는 자', labelEn: 'Waterwalking', slug: 'waterwalking', value: 8232 },
    { label: '절대 집중', labelEn: 'Absolute Focus', slug: 'absoluteFocus', value: 8233 },
  ],
}, {
  label: '결의',
  labelEn: 'resolve',
  slug: 'resolve',
  value: 8400,
  imgValue: 7204,
  subRunes: [
    { label: '착취의 손아귀', labelEn: 'Grasp of the Undying', slug: 'graspOfTheUndying', value: 8437 },
    { label: '여진', labelEn: 'VeteranAfterShock', slug: 'veteranAfterShock', value: 8439 },
    { label: '수호자', labelEn: 'Guardian', slug: 'guardian', value: 8465 },
    { label: '철거', labelEn: 'Demolish', slug: 'demolish', value: 8446 },
    { label: '보호막 강타', labelEn: 'Shield Bash', slug: 'shieldBash', value: 8401 },
    { label: '재생의 바람', labelEn: 'Second Wind', slug: 'secondWind', value: 8473 },
    { label: '뼈 방패', labelEn: 'Bone Plating', slug: 'bonePlating', value: 8444 },
    { label: '소생', labelEn: 'Revitalize', slug: 'revitalize', value: 8453 },
    { label: '불굴의 의지', labelEn: 'Unflinching', slug: 'unflinching', value: 8242 },
    { label: '과잉성장', labelEn: 'Overgrowth', slug: 'overgrowth', value: 8451 },
  ],
}, {
  label: '영감',
  labelEn: 'whimsy',
  slug: 'inspiration',
  value: 8300,
  imgValue: 7203,
  subRunes: [
    { label: '봉인 풀린 주문서', labelEn: 'Unsealed Spellbook', slug: 'unsealedSpellbook', value: 8306 },
    { label: '마법공학 점멸기', labelEn: 'Hextech Flashtraption', slug: 'hextechFlashtraption', value: 8304 },
    { label: '글레이셜 증강', labelEn: 'Glacial Augment', slug: 'glacialAugment', value: 8351 },
    { label: '완벽한 타이밍', labelEn: 'Perfect Timing', slug: 'perfectTiming', value: 8313 },
    { label: '마법의 신발', labelEn: 'Magical Footwear', slug: 'magicalFootwear', value: 8304 },
    { label: '비스킷 배달', labelEn: 'Biscuit Delivery', slug: 'biscuitDelivery', value: 8345 },
    { label: '시간 왜곡 물약', labelEn: 'Time Warp Tonic', slug: 'timeWarpTonic', value: 8347 },
    { label: '우주적 통찰력', labelEn: 'Cosmic Insight', slug: 'cosmicInsight', value: 8347 },
    { label: '접근성의 속도', labelEn: 'Approach Velocity', slug: 'approachVelocity', value: 8410 },
  ],
}]
